// Generated by dts-bundle v0.7.3

declare module 'entropy-script' {
    import { ICompileConfig, GLOBAL_CTX, now, refreshPerformanceNow, runningInNode, setGlobalContext, VERSION } from "entropy-script/src/util/constants";
    import { Error } from "entropy-script/src/errors";
    import Position from "entropy-script/src/position";
    import { CompileResult, InterpretResult } from "entropy-script/src/runtime/nodes";
    import type { ITimeData } from "entropy-script/src/util/util";
    import { Context } from "entropy-script/src/runtime/context";
    import colours from 'entropy-script/src/util/colours';
    import { config } from "entropy-script/src/config";
    export * from 'entropy-script/src/runtime/primitiveTypes';
    export { IS_NODE_INSTANCE, libs, CONFIG_FILE_NAME } from 'entropy-script/src/util/constants';
    export * from 'entropy-script/src/errors';
    export * from 'entropy-script/src/runtime/nodes';
    export * from 'entropy-script/src/util/util';
    export { strip, wrap } from 'entropy-script/src/runtime/wrapStrip';
    export { ESSymbol } from 'entropy-script/src/runtime/symbol';
    export { parseConfig } from 'entropy-script/src/config';
    import init from 'entropy-script/src/init';
    export { init, VERSION, GLOBAL_CTX as global, setGlobalContext, now, refreshPerformanceNow, ICompileConfig, runningInNode, config, Context, colours, Position, };
    export interface IRunConfig {
        env?: Context;
        measurePerformance?: boolean;
        fileName?: string;
        currentDir?: string;
        compileToJS?: boolean;
        compileJSConfig?: ICompileConfig;
    }
    export function run(msg: string, { env, measurePerformance, fileName, currentDir, compileToJS, compileJSConfig, }?: IRunConfig): {
        timeData?: ITimeData;
    } & InterpretResult;
    export function parse(code: string, { fileName, currentDir }?: {
        fileName?: string | undefined;
        currentDir?: string | undefined;
    }): {
        error: Error;
        compileToJavaScript?: undefined;
        compileToPython?: undefined;
        interpret?: undefined;
    } | {
        compileToJavaScript: (config: ICompileConfig) => CompileResult;
        compileToPython: (config: ICompileConfig) => CompileResult;
        interpret: (env?: Context) => InterpretResult;
        error?: undefined;
    };
    export { str } from "entropy-script/src/util/util";
}

declare module 'entropy-script/src/util/constants' {
    import type { Context } from 'entropy-script/src/runtime/context';
    import type { Map, EnumMap, NativeObj } from 'entropy-script/src/util/util';
    import type { ESType } from "entropy-script/src/runtime/primitives/type";
    export const DIGITS = "0123456789";
    export const IDENTIFIER_CHARS = "_$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    export const ONE_LINE_COMMENT = "//";
    export const MULTI_LINE_COMMENT_START = "/*";
    export const MULTI_LINE_COMMENT_END = "*/";
    export const WHITESPACE = " \t\n";
    export let GLOBAL_CTX: Context;
    export const setGlobalContext: (c: Context) => void;
    export const STRING_SURROUNDS: string[];
    export let IS_NODE_INSTANCE: boolean;
    export const runningInNode: () => undefined;
    export const VAR_DECLARE_KEYWORDS: string[];
    export const VERSION: any;
    export const CONFIG_FILE_NAME = "esconfig.json";
    export const VALID_FILE_ENCODINGS: string[];
    export interface ICompileConfig {
        minify: boolean;
        indent: number;
        symbols: string[];
    }
    export const types: Map<ESType>;
    export const libs: Map<NativeObj>;
    export const CATCH_BLOCK_ERR_SYMBOL_ID = "err", ANON_FUNC_NAME = "(anon)";
    export const CLASS_KEYWORDS: string[];
    export let now: () => number;
    export function refreshPerformanceNow(isNode?: boolean): void;
    export enum TokenType {
        NUMBER = 0,
        STRING = 1,
        END_STATEMENT = 2,
        IDENTIFIER = 3,
        COMMA = 4,
        ASSIGN = 5,
        ADD = 6,
        SUB = 7,
        ASTRIX = 8,
        DIV = 9,
        POW = 10,
        MOD = 11,
        OPAREN = 12,
        CPAREN = 13,
        OBRACES = 14,
        CBRACES = 15,
        OSQUARE = 16,
        CSQUARE = 17,
        EQUALS = 18,
        NOT_EQUALS = 19,
        NOT = 20,
        GT = 21,
        LT = 22,
        GTE = 23,
        LTE = 24,
        AND = 25,
        OR = 26,
        COLON = 27,
        DOT = 28,
        EOF = 29,
        PIPE = 30,
        AMPERSAND = 31,
        BITWISE_NOT = 32,
        QM = 33,
        DOUBLE_QM = 34,
        OGENERIC = 35,
        CGENERIC = 36
    }
    export const tt: typeof TokenType;
    export const ttAsStr: EnumMap<TokenType, string>;
    export const SINGLE_TOKENS: Map<TokenType>;
    export const DOUBLE_TOKENS: Map<TokenType>;
    export const TRIPLE_TOKENS: Map<TokenType>;
    export const PROPS_TO_OVERRIDE_ON_PRIM: string[];
    export const STD_RAW: string[];
}

declare module 'entropy-script/src/errors' {
    import Position from "entropy-script/src/position";
    import { Primitive } from "entropy-script/src/util/util";
    export interface TracebackFrame {
        position: Position;
        line: string;
    }
    export class Error {
        name: string;
        details: string;
        pos: Position;
        traceback: TracebackFrame[];
        constructor(name: string, details: string);
        get colouredStr(): string;
        get str(): string;
        position(pos: Position): this;
    }
    export class IllegalCharError extends Error {
        constructor(char?: string);
    }
    export class InvalidSyntaxError extends Error {
        constructor(details?: string);
    }
    export class TypeError extends Error {
        constructor(expectedType: string, actualType: string, value?: string, detail?: string);
    }
    export class ImportError extends Error {
        constructor(url: string, detail?: string);
    }
    export class ReferenceError extends Error {
        constructor(ref: string);
    }
    export class IndexError extends Error {
        constructor(ref: string, object: Primitive);
    }
    export class InvalidOperationError extends Error {
        constructor(op: string, value: Primitive, detail?: string, pos?: Position);
    }
    export class InvalidRuntimeError extends Error {
        constructor();
    }
    export class TestFailed extends Error {
        constructor(detail: string);
    }
    export class PermissionRequiredError extends Error {
        constructor(detail: string);
    }
    export class MissingNativeDependencyError extends Error {
        constructor(name: string);
    }
    export class EndIterator extends Error {
        constructor();
    }
}

declare module 'entropy-script/src/position' {
    export default class Position {
        file: string;
        idx: number;
        ln: number;
        col: number;
        constructor(idx: number, ln: number, col: number, file?: string);
        advance(currentChar?: string): this;
        get clone(): Position;
        get str(): string;
        get isUnknown(): boolean;
        static get void(): Position;
    }
}

declare module 'entropy-script/src/runtime/nodes' {
    import { Token } from "entropy-script/src/parse/tokens";
    import { Error } from "entropy-script/src/errors";
    import { Context } from 'entropy-script/src/runtime/context';
    import Position from "entropy-script/src/position";
    import { ICompileConfig } from "entropy-script/src/util/constants";
    import { IUninterpretedArgument } from "entropy-script/src/runtime/argument";
    import { ESObject, Primitive } from "entropy-script/src/runtime/primitiveTypes";
    import { Map } from 'entropy-script/src/util/util';
    export class InterpretResult {
        val: Primitive;
        error: Error | undefined;
        funcReturn: Primitive | undefined;
        shouldBreak: boolean;
        shouldContinue: boolean;
        constructor(val?: Primitive | Error);
    }
    export class CompileResult {
        val: string;
        hoisted: string;
        error: Error | undefined;
        constructor(val?: string | Error);
        register(node: Node, config: ICompileConfig): string;
    }
    export abstract class Node {
        pos: Position;
        isTerminal: boolean;
        static interprets: number;
        static totalTime: number;
        static maxTime: number;
        protected constructor(pos: Position, isTerminal?: boolean);
        abstract interpret_(context: Context): Error | InterpretResult;
        interpret(context: Context): InterpretResult;
        abstract compileJS(config: ICompileConfig): CompileResult;
        abstract compilePy(config: ICompileConfig): CompileResult;
        abstract str(): string;
    }
    export class N_binOp extends Node {
        left: Node;
        right: Node;
        opTok: Token;
        constructor(pos: Position, left: Node, opTok: Token, right: Node);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_unaryOp extends Node {
        a: Node;
        opTok: Token;
        constructor(pos: Position, a: Node, opTok: Token);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_varAssign extends Node {
        value: Node;
        varNameTok: Token<string>;
        isGlobal: boolean;
        isConstant: boolean;
        isDeclaration: boolean;
        assignType: string;
        type: Node;
        constructor(pos: Position, varNameTok: Token<string>, value: Node, assignType?: string, isGlobal?: boolean, isConstant?: boolean, isDeclaration?: boolean, type?: Primitive | Node);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_destructAssign extends Node {
        value: Node;
        varNames: string[];
        types: Node[];
        isGlobal: boolean;
        isConstant: boolean;
        constructor(pos: Position, varNames: string[], types: Node[], value: Node, isGlobal?: boolean, isConstant?: boolean);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_if extends Node {
        comparison: Node;
        ifTrue: Node;
        ifFalse: Node | undefined;
        constructor(pos: Position, comparison: Node, ifTrue: Node, ifFalse: Node | undefined);
        interpret_(context: Context): InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_while extends Node {
        comparison: Node;
        loop: Node;
        constructor(pos: Position, comparison: Node, loop: Node);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_for extends Node {
        array: Node;
        body: Node;
        identifier: Token<string>;
        isGlobalId: boolean;
        isConstId: boolean;
        constructor(pos: Position, body: Node, array: Node, identifier: Token<string>, isGlobalIdentifier: boolean, isConstIdentifier: boolean);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_array extends Node {
        items: Node[];
        shouldClone: boolean;
        constructor(pos: Position, items: Node[], shouldClone?: boolean);
        interpret_(context: Context): InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_objectLiteral extends Node {
        properties: [Node, Node][];
        constructor(pos: Position, properties: [Node, Node][]);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_statements extends Node {
        items: Node[];
        topLevel: boolean;
        constructor(pos: Position, items: Node[], topLevel?: boolean);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_functionCall extends Node {
        to: Node;
        arguments: Node[];
        indefiniteKwargs: Node[];
        definiteKwargs: Map<Node>;
        optionallyChained: boolean;
        functionType: '__call__' | '__generic__';
        constructor(pos: Position, to: Node, args?: Node[], indefiniteKwargs?: Node[], definiteKwargs?: Map<Node>, functionType?: '__call__' | '__generic__', optionallyChained?: boolean);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_functionDefinition extends Node {
        body: Node;
        arguments: IUninterpretedArgument[];
        name: string | undefined;
        this_: ESObject;
        returnType: Node;
        description: string;
        isDeclaration: boolean;
        allowArgs: boolean;
        allowKwargs: boolean;
        constructor(pos: Position, body: Node, argNames: IUninterpretedArgument[], returnType: Node, name?: string, this_?: ESObject, description?: string);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_return extends Node {
        value: Node | undefined;
        constructor(pos: Position, value: Node | undefined);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_yield extends Node {
        value: Node | undefined;
        constructor(pos: Position, value: Node | undefined);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_indexed extends Node {
        base: Node;
        index: Node;
        value: Node | undefined;
        assignType: string | undefined;
        isOptionallyChained: boolean;
        constructor(pos: Position, base: Node, index: Node, isOptionallyChained?: boolean);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_class extends Node {
        init: N_functionDefinition | undefined;
        methods: N_functionDefinition[];
        staticMethods: N_functionDefinition[];
        name?: string;
        extends_?: Node;
        isDeclaration: boolean;
        abstract: boolean;
        properties: Map<Node>;
        staticProperties: Map<Node>;
        genericParams: IUninterpretedArgument[];
        constructor(pos: Position, methods: N_functionDefinition[], properties: Map<Node>, staticMethods: N_functionDefinition[], staticProperties: Map<Node>, genericParams: IUninterpretedArgument[], extends_?: Node, init?: N_functionDefinition, name?: string, isDeclaration?: boolean, abstract?: boolean);
        interpret_(context: Context): InterpretResult | Error;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_namespace extends Node {
        name?: Node;
        mutable: boolean;
        constructor(pos: Position, statements: Node, name?: Node, mutable?: boolean, isDeclaration?: boolean);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_tryCatch extends Node {
        body: Node;
        catchBlock: Node;
        constructor(pos: Position, body: Node, catchBlock: Node);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(config: ICompileConfig): CompileResult;
        compilePy(config: ICompileConfig): CompileResult;
        str(): string;
    }
    export class N_number extends Node {
        a: Token<number>;
        constructor(pos: Position, a: Token<number>);
        interpret_(): InterpretResult | Error;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_string extends Node {
        a: Token<string>;
        constructor(pos: Position, a: Token<string>);
        interpret_(): InterpretResult | Error;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_variable extends Node {
        a: Token<string>;
        constructor(a: Token<string>);
        interpret_(context: Context): Error | InterpretResult;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_undefined extends Node {
        constructor(pos?: Position);
        interpret_(): InterpretResult;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_break extends Node {
        constructor(pos: Position);
        interpret_(): InterpretResult;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_continue extends Node {
        constructor(pos: Position);
        interpret_(): InterpretResult;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
    export class N_primitiveWrapper extends Node {
        value: Primitive;
        constructor(val: Primitive, pos?: Position);
        interpret_(): InterpretResult;
        compileJS(): CompileResult;
        compilePy(): CompileResult;
        str(): string;
    }
}

declare module 'entropy-script/src/util/util' {
    import type { Error } from 'entropy-script/src/errors';
    import type { Context } from 'entropy-script/src/runtime/context';
    import type { ESArray, ESBoolean, ESErrorPrimitive, ESFunction, ESJSBinding, ESNull, ESObject, ESString, ESType } from 'entropy-script/src/runtime/primitiveTypes';
    import { ESNumber } from 'entropy-script/src/runtime/primitiveTypes';
    import { ESPrimitive } from "entropy-script/src/runtime/primitive";
    export type EnumMap<T extends number, U = any> = {
        [key in T]: U;
    };
    export type Map<T = any> = {
        [key in string | number | symbol]: T;
    };
    export interface ITimeData {
        total: number;
        lexerTotal: number;
        parserTotal: number;
        interpretTotal: number;
        nodeMax: number;
        nodeAvg: number;
        nodeTotal: number;
        interprets: number;
    }
    export type NativeObj = any;
    export type Primitive = ESPrimitive<NativeObj> | ESJSBinding | ESString | ESType | ESNumber | ESNull | ESBoolean | ESArray | ESObject | ESFunction | ESErrorPrimitive;
    export interface IFuncProps {
        context: Context;
        kwargs?: Map<Primitive>;
        dontTypeCheck?: boolean;
    }
    export type BuiltInFunction = (config: IFuncProps, ...args: Primitive[]) => void | Error | Primitive | Promise<void>;
    export function isDigit(n: string): boolean;
    export const sleep: (ms: number) => Promise<void>;
    export function indent(str: string, { depth, by, indentStart }?: {
        depth?: number | undefined;
        by?: number | undefined;
        indentStart?: boolean | undefined;
    }): string;
    export function generateRandomSymbol(symbols: string[], length?: number, characters?: string): string;
    export function str(val: unknown, depth?: number): string;
}

declare module 'entropy-script/src/runtime/context' {
    import { Error } from "entropy-script/src/errors";
    import { ESFunction, Primitive } from "entropy-script/src/runtime/primitiveTypes";
    import { Map } from "entropy-script/src/util/util";
    import { ESSymbol, ISymbolOptions } from 'entropy-script/src/runtime/symbol';
    export class Context {
        initialisedAsGlobal: boolean;
        deleted: boolean;
        path_: string;
        get path(): string;
        set path(val: string);
        get parent(): Context | undefined;
        set parent(val: Context | undefined);
        has(identifier?: string): boolean;
        hasOwn(identifier: string): boolean;
        get(identifier: string): Primitive | Error | undefined;
        getSymbolTableAsDict(): Map<ESSymbol>;
        getSymbol(identifier: string): undefined | ESSymbol | Error;
        set(identifier: string, value: Primitive, options?: ISymbolOptions): void | Error;
        setOwn(identifier: string, value: Primitive, options?: ISymbolOptions): void | Error;
        remove(identifier: string): Error | true;
        clear(): void;
        get root(): Context;
        get keys(): string[];
        clone(): Context;
        log(): void;
    }
    export function generateESFunctionCallContext(self: ESFunction, args: Primitive[], kwargs: Map<Primitive>, parent: Context, dontTypeCheck: boolean): Context | Error;
}

declare module 'entropy-script/src/util/colours' {
    import type { Map } from 'entropy-script/src/util/util';
    const c: Map<(s: string | undefined) => string>;
    export default c;
}

declare module 'entropy-script/src/config' {
    import type { Map } from "entropy-script/src/util/util";
    export type Permissions = {
        networking: boolean;
        imports: boolean;
        accessDOM: boolean;
        useSTD: boolean;
        fileSystem: boolean;
    } & Map;
    export function defaultPermissions(): Permissions;
    interface IConfiguration {
        permissions: Permissions;
        modules: Map;
    }
    export const config: IConfiguration;
    export function parseConfig(configJSON: Map): void;
    export {};
}

declare module 'entropy-script/src/runtime/primitiveTypes' {
    import type { IFunctionInfo } from 'entropy-script/src/runtime/info';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { ESArray } from 'entropy-script/src/runtime/primitives/array';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESErrorPrimitive } from 'entropy-script/src/runtime/primitives/error';
    import { ESFunction } from 'entropy-script/src/runtime/primitives/function';
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    import { ESObject } from 'entropy-script/src/runtime/primitives/object';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESType } from 'entropy-script/src/runtime/primitives/type';
    import { ESNull } from 'entropy-script/src/runtime/primitives/null';
    import { ESNamespace } from 'entropy-script/src/runtime/primitives/namespace';
    import { ESJSBinding } from "entropy-script/src/runtime/primitives/jsbinding";
    import { Primitive } from "entropy-script/src/util/util";
    export { ESArray, ESBoolean, ESErrorPrimitive, ESFunction, ESNumber, ESPrimitive, ESString, ESObject, ESType, ESNull, ESNamespace, ESJSBinding, Primitive, IFunctionInfo };
    export function initPrimitiveTypes(): void;
}

declare module 'entropy-script/src/runtime/wrapStrip' {
    import { IFuncProps, Primitive, NativeObj } from 'entropy-script/src/util/util';
    export function wrap(thing: any, functionsTakeProps?: boolean): Primitive;
    export function strip(thing: Primitive | undefined, props: IFuncProps): NativeObj;
}

declare module 'entropy-script/src/runtime/symbol' {
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { IFuncProps, Primitive } from "entropy-script/src/util/util";
    export interface ISymbolOptions {
        isConstant?: boolean;
        isAccessible?: boolean;
        global?: boolean;
        forceThroughConst?: boolean;
        type?: Primitive;
    }
    export class ESSymbol {
        isConstant: boolean;
        value: Primitive;
        identifier: string;
        isAccessible: boolean;
        type: Primitive;
        constructor(value: Primitive, identifier: string, options?: ISymbolOptions);
        clone: (props: IFuncProps) => ESSymbol;
        str: () => ESString;
    }
}

declare module 'entropy-script/src/init' {
    import { NativeObj } from 'entropy-script/src/index';
    import { Context } from "entropy-script/src/runtime/context";
    import { Error } from "entropy-script/src/errors";
    import { Map } from "entropy-script/src/util/util";
    export default function init({ print, input, node, context, path, libs }?: {
        print?: (...args: any[]) => void;
        input?: (msg: string, cb: (...arg: any[]) => any) => void;
        node?: boolean;
        context?: Context;
        path?: string;
        libs?: Map<[NativeObj, boolean]>;
    }): Promise<Error | Context>;
}

declare module 'entropy-script/src/runtime/primitives/type' {
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Error } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import type { ESFunction } from 'entropy-script/src/runtime/primitives/function';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import type { IFuncProps, Map, Primitive } from 'entropy-script/src/util/util';
    import type { IRuntimeArgument } from "entropy-script/src/runtime/argument";
    export class ESType extends ESPrimitive<undefined> {
        readonly __primordial__: boolean;
        readonly __name__: string;
        readonly __extends__: undefined | ESType;
        readonly __methods__: ESFunction[];
        readonly __properties__: Map<Primitive>;
        readonly __abstract__: boolean;
        readonly __type_id__: string;
        __generic_types__: Primitive[];
        readonly __gargs__: IRuntimeArgument[];
        constructor(isPrimitive?: boolean, name?: string, methods?: ESFunction[], properties?: Map<Primitive>, extends_?: ESType, gargs?: IRuntimeArgument[], abstract?: boolean, id?: string);
        clone: () => ESType;
        isa: (props: IFuncProps, type: Primitive) => ESBoolean;
        cast: () => Error;
        __generics_match__: (props: IFuncProps, generics: Primitive[], instance: Primitive) => ESBoolean | Error;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __subtype_of__: (props: IFuncProps, t: Primitive) => ESBoolean | Error;
        __eq__: (_: IFuncProps, t: Primitive) => ESBoolean | Error;
        __call__: (props: IFuncProps, ...params: Primitive[]) => Error | Primitive;
        str: () => ESString;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __get__: (_: IFuncProps, k: Primitive) => Primitive | Error;
        __pipe__: (_: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (_: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
        __get_init__: () => ESFunction | undefined;
        __generic__: (props: IFuncProps, ...args: Primitive[]) => Error | Primitive;
    }
    export class ESTypeUnion extends ESType {
        readonly __left__: Primitive;
        readonly __right__: Primitive;
        constructor(left: Primitive, right: Primitive);
        __call__: () => Error | Primitive;
        __includes__: (props: IFuncProps, t: Primitive) => ESBoolean | Error;
        __subtype_of__: (props: IFuncProps, t: Primitive) => ESBoolean | Error;
        clone: () => ESType;
        __eq__: (props: IFuncProps, t: Primitive) => Error | ESBoolean;
        __generic__: () => Error | Primitive;
    }
    export class ESTypeNot extends ESType {
        constructor(type: Primitive);
        __call__: () => Error | Primitive;
        __includes__: (props: IFuncProps, t: Primitive) => ESBoolean | Error;
        __subtype_of__: (props: IFuncProps, t: Primitive) => ESBoolean | Error;
        clone: () => ESTypeNot;
        __eq__: (props: IFuncProps, t: Primitive) => Error | ESBoolean;
        __generic__: () => Error | Primitive;
    }
}

declare module 'entropy-script/src/parse/tokens' {
    import type Position from "entropy-script/src/position";
    import type { TokenType } from 'entropy-script/src/util/constants';
    import type { NativeObj } from "entropy-script/src/util/util";
    export class Token<T extends ({
        toString: any;
    } | undefined) = any> {
        type: TokenType;
        value: T;
        pos: Position;
        constructor(pos: Position, type: TokenType, value: T);
        matches(type: TokenType, val: NativeObj): boolean;
        str(): string;
    }
}

declare module 'entropy-script/src/runtime/argument' {
    import { Primitive } from "entropy-script/src/runtime/primitiveTypes";
    import { Context } from "entropy-script/src/runtime/context";
    import { Error } from "entropy-script/src/errors";
    import { Node } from "entropy-script/src/runtime/nodes";
    export interface IRuntimeArgument {
        name: string;
        type: Primitive;
        defaultValue?: Primitive;
        isKwarg?: boolean;
    }
    export interface IUninterpretedArgument {
        name: string;
        type: Node;
        defaultValue?: Node;
        isKwarg?: boolean;
    }
    export function interpretArgument(arg: IUninterpretedArgument, context: Context): IRuntimeArgument | Error;
}

declare module 'entropy-script/src/runtime/primitive' {
    import { Error, TypeError } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import type { ESString } from 'entropy-script/src/runtime/primitives/string';
    import type { Info } from 'entropy-script/src/runtime/info';
    import { IFuncProps, NativeObj, Primitive } from 'entropy-script/src/util/util';
    import type { ESNumber } from "entropy-script/src/runtime/primitives/number";
    export interface ESPrimitive<T> {
        __add__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __subtract__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __multiply__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __divide__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __pow__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __mod__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __gt__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __lt__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __and__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __or__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __bool__: (props: IFuncProps) => ESBoolean | Error;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __set__: (props: IFuncProps, key: string | Primitive, value: Primitive) => void | Error;
        __call__: (props: IFuncProps, ...parameters: Primitive[]) => Error | Primitive;
        __generic__: (props: IFuncProps, ...parameters: Primitive[]) => Error | Primitive;
        __iter__: (props: IFuncProps) => Error | Primitive;
        __next__: (props: IFuncProps) => Error | Primitive;
        __nilish__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        isa: (props: IFuncProps, type: Primitive) => ESBoolean | Error;
        is: (props: IFuncProps, obj: Primitive) => ESBoolean;
        __type_name__: () => string;
        has_property: (props: IFuncProps, key: Primitive) => ESBoolean;
    }
    export abstract class ESPrimitive<T> {
        __value__: T;
        __type__: Primitive;
        __info__: Info;
        __iterable__: boolean;
        __null__: boolean;
        protected _: NativeObj;
        protected constructor(value: T, type?: Primitive | false);
        abstract str: (props: IFuncProps, depth: ESNumber) => ESString;
        abstract cast: (config: IFuncProps, type: Primitive) => Primitive | Error;
        __add__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __subtract__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __multiply__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __divide__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __pow__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __mod__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __eq__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __gt__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __lt__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __and__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __or__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __bool__: (props: IFuncProps) => Error | ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __ampersand__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        __set__: (props: IFuncProps, key: string | Primitive, value: Primitive) => void | Error;
        abstract __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        __call__: (props: IFuncProps, ...parameters: Primitive[]) => Error | Primitive;
        __generic__: (props: IFuncProps, ...parameters: Primitive[]) => Error | Primitive;
        __iter__: (props: IFuncProps) => Error | Primitive;
        __next__: (props: IFuncProps) => Error | Primitive;
        __nilish__: (props: IFuncProps, n: Primitive) => Error | Primitive;
        abstract bool(props: IFuncProps): ESBoolean;
        abstract clone: (props: IFuncProps) => Primitive;
        isa: (props: IFuncProps, type: Primitive) => Error | ESBoolean;
        is: (props: IFuncProps, obj: Primitive) => ESBoolean;
        abstract keys: (props: IFuncProps) => (ESString | ESNumber)[];
        __type_name__: () => string;
        has_property: (props: IFuncProps, key: Primitive) => ESBoolean;
        describe: (_: IFuncProps, info: Primitive) => void;
        detail: (props: IFuncProps, info: Primitive) => TypeError | undefined;
        abstract __includes__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        abstract __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
    }
}

declare module 'entropy-script/src/runtime/info' {
    export type Info = IPrimitiveInfo & IFunctionInfo & IObjectInfo;
    export interface IPrimitiveInfo {
        name?: string;
        description?: string;
        file?: string;
        helpLink?: string;
        builtin?: boolean;
    }
    export interface IArgInfo {
        name?: string;
        type?: string;
        description?: string;
        required?: boolean;
        default_value?: string;
    }
    export interface IFunctionInfo extends IPrimitiveInfo {
        args?: IArgInfo[];
        returns?: string;
        returnType?: string;
        allow_args?: boolean;
        allow_kwargs?: boolean;
    }
    export interface IObjectInfo extends IPrimitiveInfo {
        contents?: Info[];
    }
}

declare module 'entropy-script/src/runtime/primitives/array' {
    import { Error } from 'entropy-script/src/errors';
    import { IFuncProps, Primitive } from 'entropy-script/src/util/util';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Iterable } from "entropy-script/src/runtime/primitives/iterable";
    export class ESArray extends ESPrimitive<Primitive[]> implements Iterable {
        __iterable__: boolean;
        constructor(values?: Primitive[]);
        len: () => ESNumber;
        cast: (props: IFuncProps, type: Primitive) => Primitive | Error;
        str: (props: IFuncProps, depth?: ESNumber) => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __add__: (props: IFuncProps, n: Primitive) => ESArray | Error;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __get__: (props: IFuncProps, key: Primitive) => Primitive;
        __set__: (props: IFuncProps, key: Primitive | string, value: Primitive) => void;
        contains: (props: IFuncProps, val: Primitive) => ESBoolean;
        clone: () => ESArray;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __iter__: () => ESArray;
        __next__: () => Error | Primitive;
        keys: () => (ESString | ESNumber)[];
        add: (props: IFuncProps, ...args: Primitive[]) => void;
    }
}

declare module 'entropy-script/src/runtime/primitives/boolean' {
    import { Error, TypeError } from 'entropy-script/src/errors';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { IFuncProps, Primitive } from 'entropy-script/src/util/util';
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    export class ESBoolean extends ESPrimitive<boolean> {
        constructor(val?: boolean);
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        cast: (props: IFuncProps, type: Primitive) => Error | ESNumber;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __bool__: () => this;
        __and__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __or__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        str: () => ESString;
        clone: () => ESBoolean;
        bool: () => this;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
    }
}

declare module 'entropy-script/src/runtime/primitives/error' {
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Error } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import type { IFuncProps, Primitive } from "entropy-script/src/util/util";
    export class ESErrorPrimitive extends ESPrimitive<Error> {
        constructor(error?: Error);
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        cast: () => Error;
        str: () => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        clone: () => ESErrorPrimitive;
        __includes__: () => Error;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
    }
}

declare module 'entropy-script/src/runtime/primitives/function' {
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Error } from 'entropy-script/src/errors';
    import { BuiltInFunction, IFuncProps, Primitive } from 'entropy-script/src/util/util';
    import { IUninterpretedArgument } from 'entropy-script/src/runtime/argument';
    import { Context } from 'entropy-script/src/runtime/context';
    import { Node } from 'entropy-script/src/runtime/nodes';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESObject } from 'entropy-script/src/runtime/primitives/object';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    export class ESFunction extends ESPrimitive<Node | BuiltInFunction> {
        __args__: IUninterpretedArgument[];
        __this__: ESObject;
        __returns__: Primitive;
        __closure__: Context;
        __allow_args__: boolean;
        __allow_kwargs__: boolean;
        __take_call_context_as_closure__: boolean;
        constructor(func?: Node | BuiltInFunction, arguments_?: IUninterpretedArgument[], name?: string, this_?: ESObject, returnType?: Primitive, closure?: Context, takeCallContextAsClosure?: boolean, allowArgs?: boolean, allowKwargs?: boolean);
        cast: () => Error;
        get name(): string;
        set name(v: string);
        clone: () => ESFunction;
        valueOf: () => this;
        str: () => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __call__: ({ context, kwargs, dontTypeCheck }: IFuncProps, ...params: Primitive[]) => Error | Primitive;
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        __includes__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => Error | ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
    }
}

declare module 'entropy-script/src/runtime/primitives/number' {
    import { Error, TypeError } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { IFuncProps, Primitive } from 'entropy-script/src/util/util';
    export class ESNumber extends ESPrimitive<number> {
        constructor(value?: number);
        cast: (props: IFuncProps, type: Primitive) => Primitive | Error;
        str: () => ESString;
        __add__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __subtract__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __multiply__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __divide__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __pow__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __mod__: (props: IFuncProps, n: Primitive) => ESNumber | TypeError;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __gt__: (props: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __lt__: (props: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        clone: () => ESNumber;
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
    }
}

declare module 'entropy-script/src/runtime/primitives/object' {
    import { Error } from 'entropy-script/src/errors';
    import { IFuncProps, Map, Primitive } from 'entropy-script/src/util/util';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Iterable } from "entropy-script/src/runtime/primitives/iterable";
    export class ESObject extends ESPrimitive<Map<Primitive>> implements Iterable {
        __iterable__: boolean;
        __type_map__: Map<Primitive> | undefined;
        constructor(val?: Map<Primitive>);
        cast: (props: IFuncProps, type: Primitive) => Error | ESNumber;
        str: (props: IFuncProps, depth?: ESNumber) => ESString;
        keys: () => ESString[];
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __add__: (props: IFuncProps, n: Primitive) => Error | ESObject;
        __subtract__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __get__: (props: IFuncProps, k: Primitive) => Primitive | Error;
        __set__: (props: IFuncProps, key: Primitive | string, value: Primitive) => void | Error;
        has_property: (props: IFuncProps, k: Primitive) => ESBoolean;
        clone: () => ESObject;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean | Error;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __iter__: () => Error | Primitive;
        len: () => ESNumber;
        contains: (props: IFuncProps, k: Primitive) => ESBoolean;
    }
}

declare module 'entropy-script/src/runtime/primitives/string' {
    import { Error, TypeError } from 'entropy-script/src/errors';
    import { IFuncProps, Primitive } from 'entropy-script/src/util/util';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { Iterable } from "entropy-script/src/runtime/primitives/iterable";
    export class ESString extends ESPrimitive<string> implements Iterable {
        __iterable__: boolean;
        constructor(value?: string);
        str: () => this;
        cast: (_: IFuncProps, type: Primitive) => Primitive | Error;
        __add__: (_: IFuncProps, n: Primitive) => ESString | TypeError;
        __multiply__: (_: IFuncProps, n: Primitive) => ESString | TypeError;
        __eq__: (_: IFuncProps, n: Primitive) => ESBoolean;
        __gt__: (_: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __lt__: (_: IFuncProps, n: Primitive) => ESBoolean | TypeError;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        len: () => ESNumber;
        clone: () => ESString;
        __get__: (_: IFuncProps, key: Primitive) => Primitive;
        __set__: (props: IFuncProps, key: Primitive | string, value: Primitive) => void;
        __includes__: (_: IFuncProps, n: Primitive) => ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __pipe__: (_: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (_: IFuncProps, n: Primitive) => Primitive | Error;
        __iter__: () => Error | Primitive;
        keys: () => (ESString | ESNumber)[];
        contains: (_: IFuncProps, n: Primitive) => ESBoolean | TypeError;
    }
}

declare module 'entropy-script/src/runtime/primitives/null' {
    import { Error } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { IFuncProps, Primitive } from 'entropy-script/src/util/util';
    export class ESNull extends ESPrimitive<undefined> {
        __null__: boolean;
        constructor();
        cast: () => Primitive | Error;
        str: () => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        clone: () => ESNull;
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        keys: () => ESString[];
    }
}

declare module 'entropy-script/src/runtime/primitives/namespace' {
    import { Error } from 'entropy-script/src/errors';
    import type { Map, IFuncProps, Primitive } from 'entropy-script/src/util/util';
    import { ESSymbol } from 'entropy-script/src/runtime/symbol';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import type { Iterable } from "entropy-script/src/runtime/primitives/iterable";
    import { ESNumber } from "entropy-script/src/runtime/primitives/number";
    export class ESNamespace extends ESPrimitive<Map<ESSymbol>> implements Iterable {
        __mutable__: boolean;
        __iterable__: boolean;
        constructor(name: ESString, value: Map<ESSymbol>, mutable?: boolean);
        cast: () => Error;
        get name(): ESString;
        set name(v: ESString);
        clone: () => Primitive;
        str: () => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __get__: (props: IFuncProps, key: Primitive) => Primitive | Error;
        __set__: (props: IFuncProps, key: Primitive | string, value: Primitive) => void | Error;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __iter__: (_: IFuncProps) => Error | Primitive;
        len: () => ESNumber;
        keys: () => ESString[];
        contains: (props: IFuncProps, key: Primitive) => ESBoolean;
    }
}

declare module 'entropy-script/src/runtime/primitives/jsbinding' {
    import { Error } from 'entropy-script/src/errors';
    import { ESBoolean } from 'entropy-script/src/runtime/primitives/boolean';
    import { ESString } from 'entropy-script/src/runtime/primitives/string';
    import { ESPrimitive } from 'entropy-script/src/runtime/primitive';
    import { IFuncProps, Primitive, NativeObj } from 'entropy-script/src/util/util';
    import { Iterable } from "entropy-script/src/runtime/primitives/iterable";
    import { ESNumber } from 'entropy-script/src/runtime/primitives/number';
    export class ESJSBinding<T = NativeObj> extends ESPrimitive<T> implements Iterable {
        functionsTakeProps: boolean;
        catchErrorsToPrimitive: boolean;
        __iterable__: boolean;
        constructor(value: T, name?: string, functionsTakeProps?: boolean, catchErrors?: boolean);
        cast: () => Error | Primitive;
        clone: () => Primitive;
        str: (props: IFuncProps, depth?: ESNumber) => ESString;
        __eq__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __bool__: () => ESBoolean;
        bool: () => ESBoolean;
        __get__: (props: IFuncProps, k: Primitive) => Primitive | Error;
        __set__: (props: IFuncProps, k: Primitive | string, value: Primitive) => void | Error;
        __call__: (props: IFuncProps, ...args: Primitive[]) => Error | Primitive;
        has_property: (props: IFuncProps, key: Primitive) => ESBoolean;
        __includes__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __subtype_of__: (props: IFuncProps, n: Primitive) => ESBoolean;
        __pipe__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __ampersand__: (props: IFuncProps, n: Primitive) => Primitive | Error;
        __iter__: () => Error | Primitive;
        len: () => ESNumber;
        keys: () => ESString[];
        contains: (props: IFuncProps, key: Primitive) => ESBoolean;
    }
}

declare module 'entropy-script/src/runtime/primitives/iterable' {
    import type { IFuncProps, Primitive } from "entropy-script/src/util/util";
    import type { ESNumber } from "entropy-script/src/runtime/primitives/number";
    import type { Error } from "entropy-script/src/errors";
    import type { ESBoolean } from "entropy-script/src/runtime/primitives/boolean";
    export interface Iterable {
        len: (props: IFuncProps) => ESNumber | Error;
        __iter__: (props: IFuncProps) => Error | Primitive;
        contains: (props: IFuncProps, val: Primitive) => ESBoolean | Error;
        map?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        filter?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        find?: (props: IFuncProps) => Primitive | Error;
        indexof?: (props: IFuncProps) => ESNumber | Error;
        at?: (props: IFuncProps) => Primitive | Error;
        for?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        pop?: (props: IFuncProps) => Primitive | Error;
        reduce?: (props: IFuncProps) => Primitive | Error;
        reverse?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        splice?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        insert?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        shift?: (props: IFuncProps) => (Iterable & Primitive) | Error;
        unshift?: (props: IFuncProps) => (Iterable & Primitive) | Error;
    }
}

